updating geolocation part

diff --git a/rtlsdr-ogn b/rtlsdr-ogn
--- a/rtlsdr-ogn
+++ b/rtlsdr-ogn
@@ -28,6 +28,9 @@ chroot=/mnt/ramdisk
 enable_iplocation="true"
 rtlconffile=$(grep -v "#" $conf | grep rtlsdr-ogn | grep conf | tail -1 | awk '{print $3"/"$NF}')
 iplocation_file=/tmp/iplocation.txt
+# Default coordinates if iplocation fails
+default_lat=59.3307000
+default_long=18.0718000
 
 if [ -d $chroot ]
 then
@@ -43,17 +46,26 @@ echo_failure () {
   echo " [failed]"
 }
 
+check_internet() {
+  wget -q --spider http://google.com
+  if [ $? -eq 0 ]; then
+    return 0
+  else
+    return 5
+fi
+
+}
 
 get_location () {
-   curl -s --request GET --url https://freegeoip.app/xml/ \
+   curl --request GET --url https://freegeoip.app/xml/ \
    --header 'accept: application/mxl' \
    --header 'content-type: application/xml' \
-   --output $iplocation_file || fail "curl returned an error when getting iplocation"
+   --output $iplocation_file 2>/tmp/curl.err|| fail "curl returned an error when getting iplocation"
 
   lat=$(grep "Latitude" $iplocation_file | sed 's/[^0-9,.,-]*//g' | sed 's/^\([0-9,.,-]*\)/\1000/g')
   long=$(grep "Longitude" $iplocation_file | sed 's/[^0-9,.,-]*//g' | sed 's/^\([0-9,.,-]*\)/\1000/g')
-  [[ $lat  =~ ^[+-]?[0-9]+\.?[0-9]*$ ]] || fail "wrong latitude"
-  [[ $long =~ ^[+-]?[0-9]+\.?[0-9]*$ ]] || fail "wrong longitude"
+  [[ $lat  =~ ^[+-]?[0-9]+\.?[0-9]*$ ]] || lat=$default_lat
+  [[ $long =~ ^[+-]?[0-9]+\.?[0-9]*$ ]] || long=$default_long
   sed -i 's/\(Latitude.*=\)\(.*; #\)/\1   '"$lat"'; #/g' $rtlconffile
   sed -i 's/\(Longitude.*=\)\(.*; #\)/\1   '"$long"'; #/g' $rtlconffile
 }
@@ -132,6 +144,8 @@ launch () {
 start () {
   [ -r $conf ] || fail "$conf not readable"
   [ -x $exe ] || fail "$exe is not executable"
+  if ! check_internet ; then sleep 60 ; fi
+  if ! check_internet ; then fail "No Internet connection" ; fi
   if [ "$enable_iplocation" = "true" ] ; then get_location ; fi
   launch $*
   touch /var/lock/$prog
